# Generated by Django 4.0.2 on 2022-02-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_hospitalmodel_hospital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital List'},
        ),
    ]
