# Generated by Django 3.2.5 on 2022-03-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospital_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name'], 'verbose_name': 'Hospital List'},
        ),
    ]
