# Generated by Django 3.2.5 on 2022-04-01 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_hospital_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\.\\-\\, ]*$', 'Only letters, periods, hyphens and commas are allowed.')]),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Please use letters only.')]),
        ),
    ]
