# Generated by Django 3.2.5 on 2022-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20220407_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
