# Generated by Django 3.2.5 on 2022-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Sample Id'),
        ),
    ]
