# Generated by Django 3.2.5 on 2022-04-07 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_sample_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-\\, ]*$', 'Only letters, numbers, periods, hyphens and commas are allowed.')], verbose_name='Sample Id'),
        ),
    ]
