# Generated by Django 3.2.5 on 2022-04-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_storage', '0003_remove_labstorage_orders'),
        ('order', '0003_alter_order_date_sample_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='labstorage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_labstorage', to='lab_storage.labstorage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sample_taken',
            field=models.DateTimeField(null=True, verbose_name='Date Sample Taken'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_id',
            field=models.CharField(max_length=255, verbose_name='Internal_Id'),
        ),
    ]
