# Generated by Django 3.2.5 on 2022-04-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220405_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='labstorage',
        ),
    ]
