# Generated by Django 3.2.5 on 2022-04-07 07:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_sample_sample_id'),
        ('hospital', '0007_auto_20220407_0713'),
        ('physician', '0002_auto_20220407_0713'),
        ('order', '0005_remove_order_labstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hospital',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_id',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-\\, ]*$', 'Only letters, numbers, periods, hyphens and commas are allowed.')], verbose_name='Internal Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='physician',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='physician.physician'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sample',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.sample'),
        ),
    ]
