# Generated by Django 3.2.5 on 2022-06-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220407_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sample_taken',
            field=models.DateField(null=True, verbose_name='Date Sample Taken'),
        ),
    ]
