# Generated by Django 3.2.5 on 2022-04-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_storage', '0002_labstorage_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labstorage',
            name='orders',
        ),
    ]
