# Generated by Django 3.2.5 on 2022-04-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_labstorage'),
        ('lab_storage', '0003_remove_labstorage_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='labstorage',
            name='orders',
            field=models.ManyToManyField(to='order.Order'),
        ),
    ]
