# Generated by Django 3.2.5 on 2022-04-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_storage', '0005_auto_20220407_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labstorage',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\.\\-\\, ]*$', 'Only letters, numbers, periods, hyphens and commas are allowed.')]),
        ),
    ]
