# Generated by Django 3.2.5 on 2022-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220407_0713'),
        ('lab_storage', '0006_alter_labstorage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labstorage',
            name='orders',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_deleted': False}, null=True, to='order.Order'),
        ),
    ]
