# Generated by Django 3.2.5 on 2022-04-07 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Please use letters only.')]),
        ),
        migrations.AlterField(
            model_name='physician',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Please use letters only.')]),
        ),
        migrations.AlterField(
            model_name='physician',
            name='middle_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Please use letters only.')]),
        ),
        migrations.AlterField(
            model_name='physician',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Please use numbers only.')]),
        ),
    ]
