# Generated by Django 4.0.2 on 2022-02-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospitalmodel_created_hospitalmodel_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalModel',
            new_name='Hospital',
        ),
    ]
